/* Dicho y Hecho — finales "tramposos" para el juego de completar.
   Cada uno dice lo mismo que el final verdadero pero con otras palabras,
   así que parece correcto aunque el refrán no se dice así. */
const TRAMPAS = {
  1: 'le tiene miedo a la vaca',
  2: 'termina en la parrilla',
  3: 'rayado tiene que salir',
  4: 'jamás será trompeta',
  5: 'no se seca nunca',
  6: 'no aumenta de peso',
  7: 'porque es la regla principal',
  8: 'del que te juzga',
  9: 'pero sabe más por anciano',
  10: 'que mil en el aire',
  11: 'hay un largo camino',
  12: 'algo de agua lleva',
  13: 'que remediar',
  14: 'se la lleva el río',
  15: 'mojá la tuya en agua',
  16: 'no la juntes',
  17: 'se le va el conejo',
  18: 'que termina roto',
  19: 'sin haberlo atrapado',
  20: 'el cielo lo acompaña',
  21: 'sale antes el sol',
  22: 'poco agarra',
  23: 'a tu calzado',
  24: 'cuchara de madera',
  25: 'no decide el grumete',
  26: 'y por la ruta vamos',
  27: 'que jamás',
  28: 'y te digo cómo sos',
  29: 'y te van a picar la cara',
  30: 'no hay pelea',
  31: 'alcanza para tres',
  32: 'cuidan a los amigos',
  33: 'con su canción',
  34: 'hasta el cajón',
  35: 'no lo bautizan',
  36: 'no se le revisa la boca',
  37: 'termina costando más',
  38: 'y mañana sin comer',
  39: 'se lleva la porción más grande',
  40: 'no toma la teta',
  41: 'al que no puede masticar',
  42: 'muere por hablar',
  43: 'no te va a morder',
  44: 'con poco alcanza',
  45: 'no traiciona',
  46: 'se puede equivocar',
  47: 'y al tinto, tinto',
  48: 'que no traiga algo bueno',
  49: 'alivio de zonzos',
  50: 'el corazón no sufre'
};
